### ISSUE TITLE
Unmocakable.Intercept compatibility issue

### ISSUE THREAD

**Issue by micheleissa** [riezebosch/Unmockable#11]
When I try to install the NuGet package for my NUnit unit test project which targets a specific platform  I get the following error:
```NU1202: Package Unmockable.Intercept 3.0.89 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Unmockable.Intercept 3.0.89 supports: netstandard2.1 (.NETStandard,Version=v2.1)```

**Comment by riezebosch** [comment]
`netstandard2.1` is implemented with `netcoreapp3.0`, see this [matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support). Will that work for you?

**Comment by micheleissa** [comment]
Not really so the unit tests project targets netcoreapp2.2 and according to the matrix your lib will only support netcore 3.0?? I don't think this is really a good thing cuz now you are forcing everybody to target 3.0

**Comment by riezebosch** [comment]
For the time being you can stay with [2.2.86](https://www.nuget.org/packages/Unmockable.Intercept/2.2.86) which still targets `netstandard2.0`. I  use a class that is only available since `netstandard2.1` and you only have to upgrade your test projects.

**Comment by riezebosch** [comment]
@micheleissa good news, found out that the available hash code and equals methods already suffice so used the oppurtunity to revert to netstandard2.0 again. 🎉
