### ISSUE TITLE
System.InvalidOperationException : variable 'x' of type 'System.String' referenced from scope '', but it is not defined

### ISSUE THREAD

**Issue by JohanLarsson** [riezebosch/Unmockable#37]
This may be me failing to understand the API but here goes:

This test passes
```cs
var execute = Unmockable.Interceptor.For<string>()
                        .Setup(x => x.Length).Returns(1)
                        .Execute(x => x.Length);
Assert.AreEqual(1, execute);
```

This fails with `System.InvalidOperationException : variable 'x' of type 'System.String' referenced from scope '', but it is not defined`
```cs
Unmockable.Interceptor.For<string>()
          .Setup(x => x.Length)
          .Returns(1)
          .Execute(x => Console.WriteLine(x.Length));
```

The example is perhaps not very good, what I'm trying to do is create a mock of `MouseButtonEventArgs` with setup for `GetPosition` that is then used in the test.

**Comment by riezebosch** [comment]
Looking into it!

**Comment by riezebosch** [comment]
It looks like you should rewrite it to something like:

```csharp
var something = Unmockable.Interceptor.For<string>()
          .Setup(x => x.Length)
          .Returns(1);

// inject something
Console.WriteLine(something.Execute(x => x.Length));
```

Like the API already describes: you create an _inteceptor_ for _string_ and _not_ for _Console.WriteLine_.

At least, that's the intended usage. Does that help? You got me thinking though.

**Comment by JohanLarsson** [comment]
Ah, I got the API wrong then. Thanks for the reply!
